### ISSUE TITLE
Does tsplay -loop ensure always-increasing PTS?

### ISSUE THREAD

**Issue by BobCu** [kynesim/tstools#37]
I need to build a server to loop static content to simulate live streams.  Every loop utility I've tried so far fails to update PTS.  The tsplay documentation is silent on this issue.  Does tsplay -loop update PTS for each loop? If so, can this be documented somewhere?  (Here would be fine: Google will find it.)

**Comment by BobCu** [comment]
Digging into the code, both PCR and PTS are updated after the first loop.

**Comment by bojanra** [comment]
When looping a transport stream you will get continuity counter errors when the file is rewinded.
This is fixed in my fork https://github.com/bojanra/tstools

**Comment by BobCu** [comment]
Hmmm... On your fork I'm still seeing PCR/PTS resetting to zero.  What's the right way to use your changes?

**Comment by BobCu** [comment]
@bojanra When using your fork, I'm seeing the PCR/PTS reset to zero after the loop.  What am I doing wrong?

**Comment by bojanra** [comment]
Use commandline switch **-renumber**  e.g.
`tsplay -loop -renumber mystream.ts 239.10.10.1:5500`

Please pull the last commit.

**Comment by BobCu** [comment]
@bojanra Still seeing PCR/PTS reset at the start of each loop.  Here's my command:
`./bin/tsplay -loop -renumber ../../BBB/B1I2_720p_480p_360p.ts 127.0.0.1:9876`
The input is an mpeg2 TS containing 1 audio stream and 3 video streams at different resolutions.

**Comment by BobCu** [comment]
@bojanra Here's the command I used to generate the file:

`    ffmpeg -i Big_Buck_Bunny_1080p_h264.mov -threads 16 \`
`        -map 0:a -map 0:v -map 0:v -map 0:v \`
`        -c:a aac -ac 2 -b:a 128k \`
`        -force_key_frames "expr:eq(mod(n,300),0)" -max_interleave_delta 0 \`
`        -x264opts rc-lookahead=300:keyint=600:min-keyint=300 \`
`        -pix_fmt yuv420p -preset veryslow -tune film -vsync cfr -x264-params "nal-hrd=cbr" \`
`        -s:v:0 1280x720 -c:v:0 libx264 -b:v:0 5000k -minrate:v:0 2000k -maxrate:v:0 2000k -bufsize:v:0 4000k \`
`        -s:v:1  854x480 -c:v:1 libx264 -b:v:1 1500k -minrate:v:1 1000k -maxrate:v:1 1000k -bufsize:v:1 2000k \`
`        -s:v:2  640x360 -c:v:2 libx264 -b:v:2  500k -minrate:v:2  500k -maxrate:v:2  500k -bufsize:v:2 1000k \`
`        -program program_num=1:title=multi_p30:st=0:st=1:st=2:st=3 \`
`        -f mpegts "B${numBlade}I${numInput}_720p_480p_360p.ts" -y`

**Comment by BobCu** [comment]
I have to give up on `tstools`: The following VLC line does correct PTS/DTS/PCR updating:

    $ cvlc $TS_FILE --sout udp:${IP_ADDR}:${PORT} --sout-keep --loop --sout-all --repeat

**Comment by bojanra** [comment]
*File to live* is not so simple.
At first you have to assure that the static content in file has correct start and correct end.
Correct start means: **PAT, PMT, I frame. **
Correct end means: the whole GOP is included and the file ends with the last frame of the last GOP.
In addition,  the content has to be encoded with closed GOP and at each restart you have to replace/correct the PCR, PTS, DTS and recalculate the CRC32 for all the corrected TS packets.

The **-renumber** options assures only the correctness of the continuity counter. This is essential for a error-free decoding according to ETSI TR 101290.

**Comment by BobCu** [comment]
The above cvlc command using a TS file generated by the above ffmpeg command does precisely what is needed: I get an endless TS stream with repeating video content (in 3 resolutions) and monotonically increasing PCR/DTS/PTS.  Please refer to the VLC code for how they did it.

**Comment by dbhat01** [comment]
> $ cvlc $TS_FILE --sout udp:${IP_ADDR}:${PORT} --sout-keep --loop --sout-all --repeat

Do all the PIDs in the stream copy? I find that data PIDs do not stream out.
